import * as React from 'react';
import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from 'react-email';

type OrderItem = {
  name: string;
  quantity: number;
  unitPrice: string;
  lineTotal: string;
};

type OrderConfirmationEmailProps = {
  customerName: string;
  orderNumber: string;
  status: string;
  totalAmount: string;
  items: OrderItem[];
};

export default function OrderConfirmationEmail({
  customerName = 'Customer',
  orderNumber = 'ORD-0001',
  status = 'PAID',
  totalAmount = '0.00',
  items = [
    {
      name: 'Demo Product',
      quantity: 1,
      unitPrice: '99.99',
      lineTotal: '99.99',
    },
  ],
}: OrderConfirmationEmailProps) {
  return (
    <Html lang="en">
      <Head />
      <Preview>Your order {orderNumber} has been completed.</Preview>

      <Body style={styles.body}>
        <Container style={styles.container}>
          <Section style={styles.header}>
            <Heading style={styles.title}>Enterprise Shop</Heading>
            <Text style={styles.subtitle}>Order Confirmation</Text>
          </Section>

          <Section style={styles.content}>
            <Heading style={styles.heading}>Thank you, {customerName}.</Heading>

            <Text style={styles.text}>
              Your order has been completed successfully.
            </Text>

            <Section style={styles.summaryBox}>
              <Text style={styles.summaryLine}>
                <strong>Order Number:</strong> {orderNumber}
              </Text>
              <Text style={styles.summaryLine}>
                <strong>Status:</strong> {status}
              </Text>
              <Text style={styles.summaryLine}>
                <strong>Total:</strong> €{totalAmount}
              </Text>
            </Section>

            <Hr style={styles.hr} />

            <Heading style={styles.sectionHeading}>Items</Heading>

            {items.map((item, index) => (
              <Section key={`${item.name}-${index}`} style={styles.itemRow}>
                <Text style={styles.itemName}>{item.name}</Text>
                <Text style={styles.itemMeta}>
                  {item.quantity} × €{item.unitPrice} = €{item.lineTotal}
                </Text>
              </Section>
            ))}

            <Hr style={styles.hr} />

            <Text style={styles.footerText}>
              This email was generated by the Enterprise E-Commerce Data Architecture Platform.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

const styles = {
  body: {
    backgroundColor: '#f5f7fb',
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    margin: '0',
    padding: '24px',
  },
  container: {
    backgroundColor: '#ffffff',
    borderRadius: '18px',
    maxWidth: '640px',
    margin: '0 auto',
    overflow: 'hidden',
    border: '1px solid #e5e7eb',
  },
  header: {
    backgroundColor: '#0f172a',
    padding: '28px 32px',
  },
  title: {
    color: '#ffffff',
    fontSize: '24px',
    margin: '0',
  },
  subtitle: {
    color: '#facc15',
    fontSize: '14px',
    margin: '8px 0 0',
  },
  content: {
    padding: '32px',
  },
  heading: {
    color: '#111827',
    fontSize: '24px',
    margin: '0 0 12px',
  },
  sectionHeading: {
    color: '#111827',
    fontSize: '18px',
    margin: '0 0 12px',
  },
  text: {
    color: '#4b5563',
    fontSize: '15px',
    lineHeight: '24px',
  },
  summaryBox: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e5e7eb',
    borderRadius: '14px',
    padding: '18px',
    margin: '24px 0',
  },
  summaryLine: {
    color: '#111827',
    fontSize: '15px',
    margin: '6px 0',
  },
  itemRow: {
    backgroundColor: '#f9fafb',
    borderRadius: '12px',
    padding: '14px 16px',
    marginBottom: '10px',
  },
  itemName: {
    color: '#111827',
    fontSize: '15px',
    fontWeight: '700',
    margin: '0 0 4px',
  },
  itemMeta: {
    color: '#6b7280',
    fontSize: '14px',
    margin: '0',
  },
  hr: {
    borderColor: '#e5e7eb',
    margin: '24px 0',
  },
  footerText: {
    color: '#6b7280',
    fontSize: '13px',
    lineHeight: '20px',
  },
} as const;
